"""interview sessions turns and assessments

Revision ID: 1ecc63c0a3d4
Revises: b60181a672b0
Create Date: 2026-09-09 15:00:50.081086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ecc63c0a3d4'
down_revision: Union[str, None] = 'b60181a672b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('skill_code', sa.String(length=80), nullable=False),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('is_declared', sa.Boolean(), nullable=False),
    sa.Column('is_evaluated', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('evaluated_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill_code', name='uq_candidate_skill_code')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_family_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('question_budget', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('coverage_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finish_reason', sa.String(length=30), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_candidate_id'), 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_job_family_id'), 'interview_sessions', ['job_family_id'], unique=False)
    op.create_table('talent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('overall_label', sa.String(length=80), nullable=False),
    sa.Column('top_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('hard_skills_score', sa.Integer(), nullable=False),
    sa.Column('soft_skills_score', sa.Integer(), nullable=False),
    sa.Column('interview_score', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.String(length=10), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inconsistencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_profiles_candidate_id'), 'talent_profiles', ['candidate_id'], unique=False)
    op.create_table('competency_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('rubric_id', sa.UUID(), nullable=True),
    sa.Column('rubric_version', sa.Integer(), nullable=False),
    sa.Column('rubric_source', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rubric_level', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('ai_invocation_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocations.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_evaluations_candidate_id'), 'competency_evaluations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_competency_evaluations_competency_id'), 'competency_evaluations', ['competency_id'], unique=False)
    op.create_index(op.f('ix_competency_evaluations_interview_session_id'), 'competency_evaluations', ['interview_session_id'], unique=False)
    op.create_table('interview_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('target_competency_id', sa.UUID(), nullable=False),
    sa.Column('question_intent', sa.String(length=20), nullable=False),
    sa.Column('references_turn_id', sa.UUID(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_invocation_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.String(length=20), nullable=True),
    sa.Column('is_follow_up', sa.Boolean(), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocations.id'], ),
    sa.ForeignKeyConstraint(['references_turn_id'], ['interview_turns.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.ForeignKeyConstraint(['target_competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_turns_session_id'), 'interview_turns', ['session_id'], unique=False)
    op.create_index(op.f('ix_interview_turns_target_competency_id'), 'interview_turns', ['target_competency_id'], unique=False)
    op.create_table('skill_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_skill_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('interview_turn_id', sa.UUID(), nullable=True),
    sa.Column('accepted_for_verification', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_skill_id'], ['candidate_skills.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['interview_turn_id'], ['interview_turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_evidences_candidate_skill_id'), 'skill_evidences', ['candidate_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_evidences_candidate_skill_id'), table_name='skill_evidences')
    op.drop_table('skill_evidences')
    op.drop_index(op.f('ix_interview_turns_target_competency_id'), table_name='interview_turns')
    op.drop_index(op.f('ix_interview_turns_session_id'), table_name='interview_turns')
    op.drop_table('interview_turns')
    op.drop_index(op.f('ix_competency_evaluations_interview_session_id'), table_name='competency_evaluations')
    op.drop_index(op.f('ix_competency_evaluations_competency_id'), table_name='competency_evaluations')
    op.drop_index(op.f('ix_competency_evaluations_candidate_id'), table_name='competency_evaluations')
    op.drop_table('competency_evaluations')
    op.drop_index(op.f('ix_talent_profiles_candidate_id'), table_name='talent_profiles')
    op.drop_table('talent_profiles')
    op.drop_index(op.f('ix_interview_sessions_job_family_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_candidate_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    # ### end Alembic commands ###
