"""cv_extractions claims and cv_builder sessions

Revision ID: 879be33e9940
Revises: 45894bdf48b8
Create Date: 2026-09-09 13:01:19.956497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '879be33e9940'
down_revision: Union[str, None] = '45894bdf48b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contract_version', sa.String(length=10), nullable=False),
    sa.Column('ai_invocation_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_by_candidate', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_invocation_id'], ['ai_invocations.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_extractions_candidate_id'), 'cv_extractions', ['candidate_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('cv_extraction_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('skill_code', sa.String(length=64), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('claimed_level', sa.Integer(), nullable=True),
    sa.Column('needs_validation', sa.Boolean(), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['cv_extraction_id'], ['cv_extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_candidate_id'), 'claims', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_claims_cv_extraction_id'), 'claims', ['cv_extraction_id'], unique=False)
    op.create_table('cv_builder_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('follow_up_asked', sa.Boolean(), nullable=False),
    sa.Column('current_question_text', sa.Text(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cv_extraction_id', sa.UUID(), nullable=True),
    sa.Column('document_storage_key', sa.String(length=500), nullable=True),
    sa.Column('document_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['cv_extraction_id'], ['cv_extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_builder_sessions_candidate_id'), 'cv_builder_sessions', ['candidate_id'], unique=False)
    op.create_table('cv_builder_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['cv_builder_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_builder_messages_session_id'), 'cv_builder_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_builder_messages_session_id'), table_name='cv_builder_messages')
    op.drop_table('cv_builder_messages')
    op.drop_index(op.f('ix_cv_builder_sessions_candidate_id'), table_name='cv_builder_sessions')
    op.drop_table('cv_builder_sessions')
    op.drop_index(op.f('ix_claims_cv_extraction_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_candidate_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_cv_extractions_candidate_id'), table_name='cv_extractions')
    op.drop_table('cv_extractions')
    # ### end Alembic commands ###
