"""interview questions bank

Revision ID: b60181a672b0
Revises: 3f5adcf29fbb
Create Date: 2026-09-09 14:22:41.766211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b60181a672b0'
down_revision: Union[str, None] = '3f5adcf29fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_family_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=20), nullable=False),
    sa.Column('block', sa.String(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evaluates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_follow_ups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('no_experience_variant', sa.Text(), nullable=True),
    sa.Column('risk_flag_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_family_id', 'question_id', name='uq_interview_question_family_qid')
    )
    op.create_index(op.f('ix_interview_questions_competency_id'), 'interview_questions', ['competency_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_job_family_id'), 'interview_questions', ['job_family_id'], unique=False)
    # NOTA (B2b): el autogenerate también propuso `op.drop_table('tts_usage_events')` porque
    # `alembic/env.py` no importaba `app.ai.voice.models` (tabla de B12, ya migrada en
    # 3f5adcf29fbb). Se quitó a mano — B2b no toca `app/ai/voice/` — y se corrigió el import
    # faltante en `env.py` para que un autogenerate futuro no vuelva a proponer borrarla.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_questions_job_family_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_competency_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    # ### end Alembic commands ###
